apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: remotecall
spec:
  hosts:
  - "*"
  gateways:
  - sfc-gateway
  http:
  - match:
    - uri:
        prefix: /transfer
    route:
    - destination:
        host: remotecall
        port:
          number: 9080
